### PR TITLE
BeAccessible: remove unneeded folder 'Tab view'

### PR DESCRIPTION
**Pull request by owenca**
Also, clean up Makefile

### CODE REVIEW

**Comment by waddlesplash** [comment]
You can even go one step further and switch to the system `libsanta`; just delete the SGB stuff from here and then change all SGB includes to be `<santa/...>`.

**Comment by owenca** [comment]
Some files (e.g., TextEntryAlert.*) from SantasGiftBag are missing from libsanta. I moved them to the src/ folder. After prefixing santa/ in the source files and editing the Makefile, I got these errors from make:
beaccessible
Is there a quick and easy way to fix the problem?

**Comment by waddlesplash** [comment]
Leave the `TextEntryAlert` etc. classes in the `SantasGiftBag` folder here then.

The quick-and-dirty solution would be to add `#define private public` just before including the ColumnListView file...

**Comment by owenca** [comment]
Then merge this PR as is for now?

**Comment by waddlesplash** [comment]
Fine.

**Pull request merged**
